### ISSUE TITLE
`configparser.NoSectionError: No section: 'nielsen'` after installation

### ISSUE THREAD

**Issue by vince-kr** [IrishPrime/Nielsen#131]
**Steps to reproduce**

Activate a venv, install Nielsen through pip, then run `nielsen --help`.

**Stack trace**

```bash
Traceback (most recent call last):
  File "/home/vince-kr/Installs/Nielsen/venv/bin/nielsen", line 5, in <module>
    from nielsen.bin.cli.main import main
  File "/home/vince-kr/Installs/Nielsen/venv/lib/python3.13/site-packages/nielsen/bin/cli/main.py", line 15, in <module>
    import nielsen.bin.cli.tv
  File "/home/vince-kr/Installs/Nielsen/venv/lib/python3.13/site-packages/nielsen/bin/cli/tv.py", line 129, in <module>
    ] = config.getboolean("nielsen", "simulate"),
        ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vince-kr/Installs/Python-3.13.0/Lib/configparser.py", line 857, in getboolean
    return self._get_conv(section, option, self._convert_to_boolean,
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                          raw=raw, vars=vars, fallback=fallback, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vince-kr/Installs/Python-3.13.0/Lib/configparser.py", line 837, in _get_conv
    return self._get(section, conv, option, raw=raw, vars=vars,
           ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                     **kwargs)
                     ^^^^^^^^^
  File "/home/vince-kr/Installs/Python-3.13.0/Lib/configparser.py", line 832, in _get
    return conv(self.get(section, option, **kwargs))
                ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vince-kr/Installs/Python-3.13.0/Lib/configparser.py", line 810, in get
    d = self._unify_values(section, vars)
  File "/home/vince-kr/Installs/Python-3.13.0/Lib/configparser.py", line 1188, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'nielsen'
```

**Workaround**

Create `~/.config/nielsen/config.ini` and add an empty `[nielsen]` section to get the expected output from `nielsen --help`.

**Comment by vince-kr** [comment]
`config.py` line 20: `config[config.default_section] = { ...` the `default_section` variable defaults to the word DEFAULT, not nielsen. So any occurrence of `config.get` (or `getboolean`) in bin/cli/main.py and bin/cli/tv.py raises a NoSectionError because the `section` argument is 'nielsen' in each case.

Easiest fix is to change `config.default_section` to `'nielsen'`, which matches the fixtures/config.ini and makes all of the existing calls work.

**Comment by IrishPrime** [comment]
Thanks for the report. This helped me clean up a few other minor issues, as well.
