### ISSUE TITLE
Fails to rename file if OMDB API call fails

### ISSUE THREAD

**Issue by IrishPrime** [IrishPrime/Nielsen#49]
```
Traceback (most recent call last):
  File "/home/irish/.local/bin/nielsen", line 11, in <module>
    load_entry_point('Nielsen==0.9.6', 'console_scripts', 'nielsen')()
  File "/home/irish/.local/lib/python3.6/site-packages/Nielsen-0.9.6-py3.6.egg/nielsen/api.py", line 253, in main
  File "/home/irish/.local/lib/python3.6/site-packages/Nielsen-0.9.6-py3.6.egg/nielsen/api.py", line 161, in process_file
  File "/home/irish/.local/lib/python3.6/site-packages/Nielsen-0.9.6-py3.6.egg/nielsen/api.py", line 70, in get_file_info
  File "/home/irish/.local/lib/python3.6/site-packages/Nielsen-0.9.6-py3.6.egg/nielsen/titles.py", line 58, in get_episode_title
  File "/home/irish/.local/lib/python3.6/site-packages/omdb-0.7.0-py3.6.egg/omdb/api.py", line 51, in imdbid
  File "/home/irish/.local/lib/python3.6/site-packages/omdb-0.7.0-py3.6.egg/omdb/api.py", line 23, in get
  File "/home/irish/.local/lib/python3.6/site-packages/omdb-0.7.0-py3.6.egg/omdb/client.py", line 104, in get
  File "/home/irish/.local/lib/python3.6/site-packages/omdb-0.7.0-py3.6.egg/omdb/client.py", line 60, in request
  File "/home/irish/.local/lib/python3.6/site-packages/requests-2.13.0-py3.6.egg/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://www.omdbapi.com/?i=tt4052886&page=1&Season=02&Episode=04&plot=short&tomatoes=False
```

If the OMDB API call fails, the `HTTPError` exception is unhandled and the process fails altogether rather than continuing on with the information it has available.

**Comment by IrishPrime** [comment]
The error in question occurred when attempting to retrieve the episode title, but could also reasonably occur when attempting to match the series with an IMDB ID. Be sure to handle this any time a web service is used in case services go down or the system running Nielsen is simply offline.

**Comment by IrishPrime** [comment]
The OMDB API now requires a paid subscription. While this issue should still be resolved, it will need to consider a different API.
