### ISSUE TITLE
--no-organize passes invalid type to configparser

### ISSUE THREAD

**Issue by IrishPrime** [IrishPrime/Nielsen#53]
Using the `--no-organize` option raises an error.

```python
Traceback (most recent call last):
  File "/home/irish/.local/bin/nielsen", line 11, in <module>
    load_entry_point('Nielsen==1.0.1', 'console_scripts', 'nielsen')()
  File "/home/irish/.local/lib/python3.6/site-packages/Nielsen-1.0.1-py3.6.egg/nielsen/api.py", line 230, in main
  File "/usr/lib/python3.6/configparser.py", line 1192, in set
    self._validate_value_types(option=option, value=value)
  File "/usr/lib/python3.6/configparser.py", line 1177, in _validate_value_types
    raise TypeError("option values must be strings")
TypeError: option values must be strings
```

**Comment by IrishPrime** [comment]
https://github.com/IrishPrime/Nielsen/blob/40d9acc51565dfe1b3a054e4c4882ed0a6f9100d/nielsen/api.py#L195-L198

The `--organize` and `--no-organize` options both store the boolean types for `True` and `False`, while the `configparser` object needs a string. Either the type stored must be changed, or the value should be cast as a string upon retrieval.
